### ISSUE TITLE
Installing the command as "mosh-scheme"

### ISSUE THREAD

**Issue by lassik** [higepon/mosh#20]
I have an unofficial [Homebrew formula for Mosh](https://github.com/lassik/homebrew-lisp/blob/master/Formula/mosh-scheme.rb).

Homebrew's official repo has another program named Mosh (a remote terminal program), so I had to install this one as `mosh-scheme`. I do this via `./configure "--program-transform-name=s@mosh@mosh-scheme@; s@_@-@"`.

This works otherwise, but the `#!` line at the top of `mosh-scheme-config` is not changed to say `mosh-scheme` instead of `mosh`. Is there any way to change it apart from writing a manual patch?

**Comment by higepon** [comment]
Thanks for trying to make it available via brew.

1) The renaming in the mosh-scheme-config.
I can't think of a good way to do it other than manual patch.
I checked https://www.gnu.org/software/gnuastro/manual/html_node/Executable-names.html.

But @okuoku may know. Assigning to him.

2) FYI I don't think you need this to install official release version of Mosh. The ./gen-git-build.sh is used only for building non released Mosh in the git repo.
https://github.com/lassik/homebrew-lisp/blob/master/Formula/mosh-scheme.rb#L16

**Comment by okuoku** [comment]
Supporting `--program-transform-name=` (or its friends `--program-prefix` `-program-suffix`) isn't too straightforward; IIRC gcc also renames other additional files such as man pages and alter its contents as well. Give me some time to check how other packages handle this.

**Comment by lassik** [comment]
> The ./gen-git-build.sh is used only for building non released Mosh in the git repo.

Fixed in https://github.com/lassik/homebrew-lisp/commit/13e0ab091d24b144c9b7770e78faed0d2ceff587

But `brew install --head lassik/lisp/mosh-scheme` still doesn't work for some reason. It fails at the `./configure` command but I don't get any obvious error message.

**Comment by lassik** [comment]
Ah, `./gen-git-build.sh` needed autotools.

It also needs a prior version of Mosh, which it expects to find by the name `mosh`. Not sure whether I can fix that using Homebrew's infrastructure.

**Comment by higepon** [comment]
You're right. Building head is not very trivial on Mac but easier on Linux on Docker.
https://github.com/higepon/mosh/tree/master/docker/dev.

I would not spend too much time to support build on head.

**Comment by higepon** [comment]
To @okuoku ,
We might be able to make it using something like the following?
https://github.com/madmurphy/libconfini/blob/master/configure.ac#L76

**Comment by okuoku** [comment]
To implement it, we need to replace every `mosh` reference inside the project. For example the project above uses `PACKAGE_CONFNAME` macro https://github.com/madmurphy/libconfini/search?q=PACKAGE_CONFNAME

In addition to Makefile, we'd need to transform man pages etc.

**Comment by higepon** [comment]
Thank you!

I think there are 2 options here.

A) Minimal support for program_transform_name

- We don't rename man pages or docs.
- We rename whatever critical. mosh-config is one of the examples.

B) Rename the default exectutable name "mosh" to something (mosh-scheme?) officially.

- This is breaking change but we can do it with a major release.
- We have rename to many things in this repo but it's just static replacement + we can test throughly with Docker or GitHub Actions.

What do you think?

**Comment by okuoku** [comment]
I feel we should adopt `--program-transform-name`. As glanced several GNU package, it seems it's enough to adjust installation paths (ie. no need to adjust documentation). 

From our filelist: https://github.com/freebsd/freebsd-ports/blob/main/lang/mosh/pkg-plist we should rename:

- bin/`mosh`
- bin/`mosh_config` (and embedded path to bin/mosh)
- bin/`nmosh`
- lib/`mosh`/*
- man/man1/`mosh`.1
- man/man1/`mosh_config`.1

`nmosh` name was specifically designed to avoid need of `nmosh-scheme` but I think it's okay since nmosh's primary use is embedded interpreter -- never to be installed to shared directories so most users do not call `nmosh` executable at all.

Re: Renaming the project officially, I'm a bit negative; about 3% of Debian installation have mosh (mobile shell) https://qa.debian.org/popcon.php?package=mosh and it's bit lower than zsh(7%) or cmake(12%) so the population affected by this is somewhat limited.

**Comment by higepon** [comment]
Sounds good. Let's go with A) then.
