### ISSUE TITLE
How to build from source

### ISSUE THREAD

**Issue by bentxt** [higepon/mosh#245]
When building from the git repo

```
./configure
config.status: error: cannot find input file: `Makefile.in'
```

```
autoreconf
...
automake: error: cannot open < automake/dist-git-revision.mk: No such file or directory
autoreconf: error: automake failed with exit status: 1
```

when I run autoupdate

```
autoupdate
...
configure.ac:482: warning: The preprocessor macro `STDC_HEADERS' is obsolete.
  Except in unusual embedded environments, you can safely include all
  ISO C90 headers unconditionally.
configure.ac:493: warning: Update your code to rely only on HAVE_SYS_TIME_H,
then remove this warning and the obsolete code below it.
All current systems provide time.h; it need not be checked for.
Not all systems provide sys/time.h, but those that do, all allow
you to include it and time.h simultaneously.
```

**Comment by okuoku** [comment]
Since part of mosh is written in mosh itself and Gauche(another Scheme implementation), you cannot build git repository straight. Please download some release tarball from https://github.com/higepon/mosh/releases . The tarball includes required files to do usual `./configure && make` flow.

Release tarball still depends on a few external libraries. Please refer https://github.com/higepon/mosh#building-and-installing-mosh for details.

**Comment by bentxt** [comment]
> Since part of mosh is written in mosh itself and Gauche(another Scheme implementation), you cannot build git repository straight

Thanks for your explanation, maybe this sentence could be inserted somewhere in the documentation

**Comment by bentxt** [comment]
with a running mosh version (pre)installed, I could then successfully run
```
gen-git-build.sh
configure 
make
```
