### ISSUE TITLE
mosh 0.2.8 RC5 or mosh-0.2.8

### ISSUE THREAD

**Issue by higepon** [higepon/mosh#55]
What do you want to do before RC5 or the final release?

**Comment by okuoku** [comment]
Need a weekend for cooldown..

- Native Windows build -- VS2013 => VS2022 migration and CMake modernization
- Confirm build on FreeBSD
- (Preferably,) Confirm build on Alpine Linux that uses Musl-libc.

In #44 , I assumed most POSIXes permissive for deprecated interfaces but [at least Darwin wasn't](https://github.com/higepon/mosh/pull/44#issuecomment-1240848477). I feel it'd also happen on alternative libc-s such as BSDs and MUSL and require us to adjust `__POSIX_C_SOURCE` occurrence more.

**Comment by higepon** [comment]
Ack.
Re: FreeBSD
When possible let's have either docker support or build support in build.yml.

**Comment by higepon** [comment]
Just want to check-in here. How's everything going.

**Comment by okuoku** [comment]
CI not so very happy(concurrent-crash test sometimes hangs, *BSD tests sometimes fail to set-up, etc) atm but otherwise it gone well mostly.

- Windows build #66 
- FreeBSD build #71 
- Alpine linux #67 

I'll add Windows native CI later (preparing pre-built dependencies: https://github.com/okuoku/nmosh-build-prerequisites ) but at least current HEAD works with Windows so I'm happy with RC or a formal release.

**Comment by higepon** [comment]
Thank you so much for the CI work!
I'm very happy to see our changes are guarded by them.

**Comment by higepon** [comment]
Checking if we're ready for RC5.

**Comment by higepon** [comment]
@okuoku I'll release RC5 tomorrow unless you need last minute change.

**Comment by higepon** [comment]
RC5 has been released. https://github.com/higepon/mosh/releases/tag/mosh-0.2.8-rc5
Thank you everyone!
